name: CICD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  sca:
    needs: build
    uses: ./.github/workflows/sca.yaml
    secrets: inherit
